vec3 a_position  : POSITION;
vec2 a_texcoord0 : TEXCOORD0;
#if defined(DIRECTIONAL_LIGHTING_PASS) || defined(DIRECTIONAL_LIGHTING_PASS0_PASS) || defined(DIRECTIONAL_LIGHTING_PASS1_PASS) || defined(DISCRETE_INDIRECT_COMBINED_LIGHTING_PASS)
vec4 a_texcoord1 : TEXCOORD1;
#endif

vec3 v_projPosition : COLOR1;
vec4 v_texcoord0    : TEXCOORD0;
#if defined(DIRECTIONAL_LIGHTING_PASS) || defined(DIRECTIONAL_LIGHTING_PASS0_PASS) || defined(DIRECTIONAL_LIGHTING_PASS1_PASS) || defined(DISCRETE_INDIRECT_COMBINED_LIGHTING_PASS)
vec4 v_tileCoords   : TEXCOORD1;
#endif